language: cpp

sudo: required
dist: trusty

compiler:
    - g++

before_install:
    - sudo apt-get update
    - sudo apt-get install libzdb-dev cppcheck cloc

script:
    - ./BUILD
    - cppcheck --enable=style,performance,portability,warning,information --inconclusive --std=posix -q -v .
    - cloc .
